import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
import {defaults} from '../backend/cloudflare/quotas.js';

test('browser administration uses header actions, handles reductions, exports data and works at mobile width',async()=>{
  const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
  const account={id:'77',identity:{id:'77',login:'demo-user',name:'Demo'},limits:defaults(),usage:{images:2,videoSeconds:30,imageDeliveries:12,videoDeliverySeconds:16,dailyUploads:1},blocked:false,unlimited:false,note:''};
  const operator={id:'228026986',identity:{id:'228026986',login:'jsw-teams',name:'JS.GRIPE'},limits:Object.fromEntries(Object.keys(defaults()).map(key=>[key,null])),usage:{images:0,videoSeconds:0,imageDeliveries:0,videoDeliverySeconds:0,dailyUploads:0},blocked:false,unlimited:true,note:''};
  const session={user:operator.identity,csrf:'fixture-csrf',isAdmin:true,account:operator,loginAvailable:true,profile:{id:operator.id,login:operator.identity.login,displayName:'JS.GRIPE',bio:''},canPublish:true,imagesAvailable:true,videosAvailable:true,maxVideoDuration:36000,maxVideoBytes:29_999_999_999};
  let change,requests=0,sessionReads=0;const errors=[],actions=[];
  try{
    const context=await browser.newContext({locale:'zh-CN',viewport:{width:1280,height:960}});
    await context.route('**/*',async route=>{const url=new URL(route.request().url());assert.equal(url.origin,'https://ishare.js.gripe');if(url.pathname==='/api'){
      assert.equal(url.search,'');const headers=route.request().headers(),action=headers['x-service-action'];actions.push(action);let body;
      if(route.request().method()==='POST'){assert.equal(headers['x-csrf-token'],'fixture-csrf');body=route.request().postDataJSON();}
      let data;
      switch(action){case 'profile-avatar':case 'avatar':return route.fulfill({contentType:'image/png',body:await readFile('content/assets/brand/bear-icon.3754101e8d6380da.png')});case 'session':{sessionReads++;const page=headers['x-service-resource'];data={...session,initial:session.user?page==='mine'?{history:{items:[],next:null}}:page==='profile'?{rights:{items:[]}}:page==='admin'?{settings:{defaults:defaults(),shared:{images:10000,videoSeconds:36000,daily:500},pending:null,note:''}}:null:null};break;}case 'erase-account':session.account.erasing=true;session.canPublish=false;data={ok:true,pending:true};break;case 'set-profile':session.profile={...session.profile,...body};data=session.profile;break;case 'logout':session.user=null;session.profile=null;session.isAdmin=false;session.account=null;session.canPublish=false;data={ok:true};break;case 'profile-feed':data={items:[{id:'a'.repeat(32),kind:'post',title:'公开的旅行记录',caption:'周末走进山里',author:{id:operator.id,name:session.profile?.displayName||'JS.GRIPE',login:'jsw-teams'},media:[],created:1,published:2,state:'published',shareUrl:'https://ishare.js.gripe/s/'+ 'a'.repeat(32)}],next:null};break;case 'history':case 'list':case 'admin-list':data={items:[],next:null};break;case 'admin-settings':data={defaults:defaults(),shared:{images:10000,videoSeconds:36000,daily:500},pending:null,note:''};break;case 'admin-users':data={items:[operator,account],next:null};break;case 'admin-user':data=account;break;case 'admin-set-user':change=body;account.note=body.note;account.notice={limits:body.limits,blocked:body.blocked,effective:Math.floor(Date.now()/1000)+604800};data=account;break;case 'rights':case 'admin-audit':case 'admin-rights':data={items:[]};break;case 'export':data={identity:operator.identity,account:operator,items:[],requests:[],next:null};break;case 'request-right':requests++;data={id:'fixture-right',due:Math.floor(Date.now()/1000)+2592000};break;default:throw Error('Unexpected action '+action);}
      return route.fulfill({contentType:'application/json',body:JSON.stringify(data)});
    }
      if(url.pathname==='/u/'+operator.id){const html=(await readFile('dist/profile-shell-zh-CN.html','utf8')).replaceAll('PROFILE_NAME_TOKEN',session.profile.displayName).replaceAll('PROFILE_BIO_TOKEN',session.profile.bio).replaceAll('PROFILE_LOGIN_TOKEN','jsw-teams').replaceAll('PROFILE_ID_TOKEN',operator.id);return route.fulfill({contentType:'text/html',body:html});}
      const path=url.pathname.endsWith('/')?url.pathname.slice(1)+'index.html':url.pathname.slice(1);try{return route.fulfill({contentType:path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.svg')?'image/svg+xml':path.endsWith('.png')?'image/png':path.endsWith('.webp')?'image/webp':'text/html',body:await readFile('dist/'+path)});}catch{if(/\.(js|css)$/.test(path))errors.push('Missing runtime asset: '+path);return route.fulfill({status:404,body:''});}
    });
    const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto('https://ishare.js.gripe/mine/');await page.locator('.privacy-settings-button').click();await page.locator('.privacy-panel').waitFor({state:'visible'});assert.equal(await page.locator('.privacy-service-setting').count(),0);await page.locator('.privacy-close').click();assert.equal(await page.locator('#admin').count(),0);await page.waitForFunction(()=>document.querySelector('#identity img')?.src.startsWith('blob:'));assert.equal(actions.includes('history'),false);assert.equal(actions.includes('rights'),false);assert.equal(await page.locator('#admin-link').isVisible(),false);await page.locator('#identity').click();assert.equal(await page.locator('#admin-link').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#account-menu').getAttribute('open'),null);await page.locator('#identity').press('ArrowDown');assert.equal(await page.locator('#profile-link').evaluate(node=>node===document.activeElement),true);await page.locator('#admin-link').click();await page.waitForURL('https://ishare.js.gripe/admin/');assert.equal(await page.locator('#publish-form, #rights').count(),0);await page.locator('#platform-settings form').waitFor();assert.equal(actions.includes('admin-settings'),false);assert.equal(actions.includes('admin-users'),false);assert.equal(actions.includes('admin-audit'),false);assert.equal(actions.includes('admin-rights'),false);assert.equal(await page.locator('#platform-settings input[type=number]:visible').count(),2);await page.locator('#tab-users').click();assert.equal(await page.locator('#tab-users').getAttribute('aria-selected'),'true');await page.locator('#admin-users button').nth(1).click();assert.equal(await page.locator('#admin-users button').nth(1).getAttribute('aria-pressed'),'true');await page.locator('#admin-editor form').waitFor();await page.locator('#tab-rights').click();await page.waitForFunction(()=>document.querySelector('#rights-queue').dataset.loaded==='true');await page.locator('#tab-users').click();await page.locator('#tab-rights').click();assert.equal(actions.filter(action=>action==='admin-rights').length,1);await page.locator('#rights-load').click();await page.waitForFunction(()=>document.querySelector('#rights-queue').textContent!=='正在加载…');assert.equal(actions.filter(action=>action==='admin-rights').length,2);await page.locator('#tab-users').click();
    await page.locator('#admin-editor').getByRole('spinbutton',{name:'图片存储（张）',exact:true}).fill('1');await page.locator('#admin-editor').getByLabel('原因（对应用户可见）').fill('演示：容量调整，提前七天通知');await page.locator('#admin-editor').getByRole('button',{name:'保存',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#admin-editor').textContent.includes('生效时间'));assert.equal(change.limits.images,1);assert.equal(change.limits.dailyUploads,50);assert.equal(change.limits.videoDuration,600);assert.equal(await page.locator('#admin-editor input[type=number]').count(),2);assert.equal(change.urgent,false);assert.equal(change.note,'演示：容量调整，提前七天通知');
    if(process.env.ISHARE_CAPTURE_DOCS==='1'){await mkdir('docs/images',{recursive:true});await page.locator('main').screenshot({path:'docs/images/admin-preview.png'});}
    await page.goto('https://ishare.js.gripe/mine/');assert.equal(await page.locator('#rights').count(),0);await page.locator('#identity').click();await page.locator('#profile-link').click();await page.waitForURL('https://ishare.js.gripe/profile/');await page.locator('[name=displayName]').fill('山里的黑熊');await page.locator('[name=bio]').fill('记录旅途的照片和故事。');assert.equal(await page.locator('#preview-name').textContent(),'山里的黑熊');await page.locator('#profile-form button').click();await page.waitForFunction(()=>document.querySelector('#status').textContent==='个人资料已保存。');assert.equal(session.profile.displayName,'山里的黑熊');assert.equal(await page.locator('#menu-name').textContent(),'山里的黑熊');await page.waitForFunction(()=>document.querySelector('#profile-avatar').src.startsWith('blob:'));
    if(process.env.ISHARE_CAPTURE_DOCS==='1'){await page.locator('main').screenshot({path:'docs/images/profile-preview.png'});await page.locator('#identity').click();await page.screenshot({path:'docs/images/account-menu.png'});await page.keyboard.press('Escape');}
    await page.locator('#public-profile-link').click();await page.waitForURL('https://ishare.js.gripe/u/'+operator.id);await page.locator('#profile-posts .post-card').waitFor();assert.equal(await page.locator('h1').textContent(),'山里的黑熊');await page.locator('.post-author img').click();await page.waitForURL('https://ishare.js.gripe/u/'+operator.id);await page.locator('#profile-posts .post-card').waitFor();
    if(process.env.ISHARE_CAPTURE_DOCS==='1')await page.locator('main').screenshot({path:'docs/images/public-profile-preview.png'});
    await page.goto('https://ishare.js.gripe/profile/');await page.locator('#rights-form textarea').fill('请人工复核我的额度');await page.getByRole('button',{name:'提交请求',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#rights-form textarea').value==='');assert.equal(requests,1);
    const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出我的数据',exact:true}).click();assert.equal((await download).suggestedFilename(),'ishare-data.json');const beforeErase=sessionReads;await page.locator('#erase').click();await page.locator('.action-dialog .button-danger').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('已申请删除'));assert.equal(sessionReads,beforeErase+1);assert.equal(await page.locator('#profile-form [name=displayName]').isDisabled(),true);assert.equal(await page.locator('#rights').isVisible(),true);
    await page.locator('#site-language').selectOption('/en/profile/');await page.waitForURL('https://ishare.js.gripe/en/profile/');assert.equal(await page.locator('html').getAttribute('lang'),'en');await page.locator('.privacy-panel').waitFor({state:'hidden'});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#identity').click();await page.locator('#logout').click();await page.locator('#profile-center').waitFor({state:'hidden'});assert.equal(await page.locator('#rights').isVisible(),false);assert.equal(await page.locator('#account-menu').isVisible(),false);assert.deepEqual(errors,[]);await context.close();
  }finally{await browser.close();}
});
