import {cp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {build} from 'esbuild';
import {buildSite} from 'edgepress/src/build.js';
const generated=resolve('.site-static');if(dirname(generated)!==process.cwd())throw new Error('Invalid generated directory');
await rm(generated,{recursive:true,force:true});await mkdir('.site-static/ishare',{recursive:true});
await cp('static','.site-static',{recursive:true});
const theme=await readFile('node_modules/edgepress/themes/default/assets/style.css','utf8');
await writeFile('.site-static/ishare/consent.css',theme.split(/\r?\n/).filter(line=>line.startsWith('.privacy-manager')||line.startsWith('.page-builder')||line.startsWith('.edgepress-oembed')||line.startsWith('@media')&&(line.includes('.privacy-manager')||line.includes('.page-builder'))).join('\n'));
await build({entryPoints:['static/ishare/player.js'],outfile:'.site-static/ishare/player.js',bundle:true,minify:true,format:'esm',target:'es2022',legalComments:'eof'});
await writeFile('.site-static/_headers',`/*\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' blob:; connect-src 'self' https://upload.imagedelivery.net https://upload.videodelivery.net; media-src 'self' blob:; worker-src 'self' blob:; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'\n/brand/*\n  Cache-Control: public, max-age=31536000, immutable\n`);
await buildSite();
await writeFile('dist/privacy.html',await readFile('dist/privacy/index.html'));
