import {readFile,writeFile} from 'node:fs/promises';
const names={image:'image',video:'film',daily:'upload',upload:'arrow-up',success:'check',error:'triangle-alert',close:'x',play:'play'};
const icons={};
for(const [key,name]of Object.entries(names))icons[key]=(await readFile('node_modules/lucide-static/icons/'+name+'.svg','utf8')).replace(/<!--[\s\S]*?-->/g,'').replace('<svg','<svg aria-hidden="true" focusable="false"').replace(/\s+/g,' ').trim();
await writeFile('static/ishare/icons.js','/*! @license Lucide Icons\n'+(await readFile('node_modules/lucide-static/LICENSE','utf8')).trim()+'\n*/\n// Generated by tools/sync-icons.mjs.\nexport const icons='+JSON.stringify(icons)+';\n');
